# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_neighbour_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='tagged',
            field=models.BooleanField(default=False),
        ),
    ]
