# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 15:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_auto_20160511_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdescription',
            name='topic1',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='topic10',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='topic11',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='topic12',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='topic13',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='topic14',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='topic15',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='topic16',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='topic17',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='topic18',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='topic19',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='topic2',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='topic20',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='topic21',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='topic22',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='topic23',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='topic24',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='topic25',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='topic3',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='topic4',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='topic5',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='topic6',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='topic7',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='topic8',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='topic9',
        ),
    ]
