# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0004_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='document',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
